apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"python-microservice"},"name":"python-microservice-deployment","namespace":"pwc"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"python-microservice"}},"template":{"metadata":{"labels":{"app":"python-microservice"}},"spec":{"containers":[{"image":"adhamelsheikh/python-microservice:latest","name":"python-microservice","ports":[{"containerPort":5000}],"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
    creationTimestamp: "2025-09-10T20:23:40Z"
    generation: 1
    labels:
      app: python-microservice
    name: python-microservice-deployment
    namespace: pwc
    resourceVersion: "74300"
    uid: e5ba3de8-c76d-4d56-b334-eeb5790b8992
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: python-microservice
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: python-microservice
      spec:
        containers:
        - image: adhamelsheikh/python-microservice:latest
          imagePullPolicy: Always
          name: python-microservice
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-09-10T20:23:40Z"
      lastUpdateTime: "2025-09-10T20:23:44Z"
      message: ReplicaSet "python-microservice-deployment-569d9457bf" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-09-12T11:01:14Z"
      lastUpdateTime: "2025-09-12T11:01:14Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
