apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins
roleRef:
  kind: ClusterRole
  name: admin  # gives full permissions in namespace
  apiGroup: rbac.authorization.k8s.io
